// Copyright (c) 2026 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/http;
import ballerina/jballerina.java;
import ballerinax/openrouter;

const DEFAULT_OPENROUTER_SERVICE_URL = "https://openrouter.ai/api/v1";
const DEFAULT_MAX_TOKEN_COUNT = 512;

# Closes the concrete span (a `ChatSpan` for `chatAsStream`, a `GenerateContentSpan` for
# `generateAsStream`) backing a streaming request.
#
# `observe:LlmSpan.close` is inherited from `observe:AiSpan` through a second level of
# `*`-inclusion, and does not resolve when called through the abstract `observe:LlmSpan`
# type from outside the `ai` module - every other `observe:LlmSpan` member does. Capturing
# `close` as a closure at the call site, where the span is still concretely typed, works
# around that and lets `openChunkStream`/`OpenRouterChunkIterator` stay span-type-agnostic.
type SpanCloser isolated function (error? err) returns ();

# ModelProvider is a client class that provides an interface for interacting with
# LLMs via the OpenRouter unified API, which supports models from OpenAI, Anthropic,
# Google, Meta, Mistral, and many other providers.
@display {
    label: "OpenRouter Model Provider"
}
public isolated distinct client class ModelProvider {
    *ai:ModelProvider;
    private final openrouter:Client openrouterClient;
    private final http:Client streamClient;
    private final string modelType;
    private final decimal? temperature;
    private final int maxTokens;
    private final openrouter:SendChatCompletionRequestHeaders & readonly requestHeaders;

    # Initializes the OpenRouter model provider with the given configuration.
    #
    # + apiKey - The OpenRouter API key (obtain from https://openrouter.ai/keys)
    # + modelType - The OpenRouter model to use (e.g., `openai/gpt-4o`, `anthropic/claude-3.5-sonnet`)
    # + serviceUrl - The base URL of the OpenRouter API endpoint
    # + siteUrl - Optional site URL sent as `HTTP-Referer` header for OpenRouter attribution
    # + siteName - Optional site name sent as `X-OpenRouter-Title` header for OpenRouter attribution
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model
    # + temperature - The temperature for controlling randomness in the model's output
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `()` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(@display {label: "API Key"} string apiKey,
            @display {label: "Model Type"} string modelType,
            @display {label: "Service URL"} string serviceUrl = DEFAULT_OPENROUTER_SERVICE_URL,
            @display {label: "Site URL"} string? siteUrl = (),
            @display {label: "Site Name"} string? siteName = (),
            @display {label: "Maximum Tokens"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal? temperature = (),
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig) returns ai:Error? {
        openrouter:Client|ai:Error openrouterClient = buildOpenRouterClient(apiKey, serviceUrl, connectionConfig);
        if openrouterClient is ai:Error {
            return openrouterClient;
        }
        http:Client|ai:Error streamClient = buildStreamClient(apiKey, serviceUrl, connectionConfig);
        if streamClient is ai:Error {
            return streamClient;
        }
        self.openrouterClient = openrouterClient;
        self.streamClient = streamClient;
        self.modelType = modelType;
        self.temperature = temperature;
        self.maxTokens = maxTokens;

        // Build optional OpenRouter attribution headers
        openrouter:SendChatCompletionRequestHeaders headers = {};
        if siteUrl is string {
            headers["HTTP-Referer"] = siteUrl;
        }
        if siteName is string {
            headers["X-OpenRouter-Title"] = siteName;
        }
        self.requestHeaders = headers.cloneReadOnly();
    }

    # Sends a chat request to the OpenRouter model with the given messages and tools.
    #
    # + messages - List of chat messages or a single user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Function to be called, chat response or an error in-case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages, ai:ChatCompletionFunctions[] tools = [],
            string? stop = ()) returns ai:ChatAssistantMessage|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("openrouter");
        if stop is string {
            span.addStopSequence(stop);
        }
        decimal? temperature = self.temperature;
        if temperature is decimal {
            span.addTemperature(temperature);
        }
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        openrouter:ChatGenerationParams request = {
            max_completion_tokens: <decimal>self.maxTokens,
            stop,
            model: self.modelType,
            messages: check self.prepareCompletionRequestMessages(messages, tools)
        };
        if temperature is decimal {
            request.temperature = temperature;
        }
        if tools.length() > 0 {
            request.tools = tools.map(t => <openrouter:ToolDefinitionJson>{
                'type: "function",
                'function: {name: t.name, description: t.description, parameters: t.parameters}
            });
            span.addTools(tools);
        }

        openrouter:ChatResponse|error response = self.openrouterClient->/chat/completions.post(
            request, self.requestHeaders);
        if response is error {
            ai:Error err = buildHttpError(response);
            span.close(err);
            return err;
        }

        openrouter:ChatResponseChoice[] choices = response.choices;
        if choices.length() == 0 {
            ai:Error err = error ai:LlmInvalidResponseError("Empty response from the model when using function call API");
            span.close(err);
            return err;
        }

        span.addResponseId(response.id);
        decimal? inputTokens = response?.usage?.prompt_tokens;
        if inputTokens is decimal {
            span.addInputTokenCount(<int>inputTokens);
        }
        decimal? outputTokens = response?.usage?.completion_tokens;
        if outputTokens is decimal {
            span.addOutputTokenCount(<int>outputTokens);
        }
        anydata finishReasonRaw = choices[0].finish_reason;
        string? finishReason = finishReasonRaw is string ? finishReasonRaw : ();
        if finishReason is string {
            span.addFinishReason(finishReason);
        }

        ai:ChatAssistantMessage|ai:Error message = self.convertResponseToAssistantMessage(choices[0].message);
        if message is ai:Error {
            span.close(message);
            return message;
        }
        if tools.length() > 0 && message.toolCalls is () {
            string finishInfo = finishReason is string ? string ` (finish_reason: '${finishReason}')` : "";
            ai:Error err = error ai:LlmInvalidResponseError(
                string `Model '${self.modelType}' did not return a tool call despite ${tools.length()} ` +
                string `tool(s) being provided${finishInfo}. The model may not support function calling, ` +
                "or it chose to respond with plain text. Try a model that supports tool use, or adjust the prompt."
            );
            span.close(err);
            return err;
        }
        span.addOutputMessages(message);
        span.addOutputType(observe:TEXT);
        span.close();
        return message;
    }

    # Sends a chat request to the model and generates a value of the type specified by
    # the `td` type descriptor. For complex record types, annotate the type with
    # `@ai:JsonSchema` to enable compile-time schema generation.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt,
            @display {label: "Expected type"} typedesc<anydata> td = <>) returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.openrouter.Generator"
    } external;

    # Sends a streaming chat request to the OpenRouter model with the given messages and tools.
    #
    # + messages - List of chat messages or a single user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - A stream of chat message chunks, or an error in case of failures
    isolated remote function chatAsStream(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools = [], string? stop = ())
            returns stream<ai:ChatMessageChunk, ai:Error?>|ai:Error {
        final observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("openrouter");
        if stop is string {
            span.addStopSequence(stop);
        }
        decimal? temperature = self.temperature;
        if temperature is decimal {
            span.addTemperature(temperature);
        }
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        openrouter:Message[]|ai:Error payloadMessages = self.prepareCompletionRequestMessages(messages, tools);
        if payloadMessages is ai:Error {
            span.close(payloadMessages);
            return payloadMessages;
        }
        openrouter:ChatGenerationParams request = {
            max_completion_tokens: <decimal>self.maxTokens,
            stop,
            model: self.modelType,
            messages: payloadMessages,
            // OpenRouter always includes full usage details on the final chunk,
            // so `stream_options.include_usage` is unnecessary (and deprecated).
            'stream: true
        };
        if temperature is decimal {
            request.temperature = temperature;
        }
        if tools.length() > 0 {
            request.tools = tools.map(t => <openrouter:ToolDefinitionJson>{
                'type: "function",
                'function: {name: t.name, description: t.description, parameters: t.parameters}
            });
            span.addTools(tools);
        }

        return self.openChunkStream(request, span, isolated function(error? err) {
            span.close(err);
        });
    }

    # Sends a streaming chat request to the model using the given prompt and streams back the
    # generated answer as text fragments. The request is built from the prompt the same way as
    # for `generate` (text and image content parts), without the structured-output tool.
    #
    # Streaming produces text only: structured types have no valid intermediate state, so use
    # `generate` for structured output.
    #
    # + prompt - The prompt to use in the chat request
    # + return - A stream of text fragments, or an error if generation fails
    isolated remote function generateAsStream(ai:Prompt prompt) returns stream<string, ai:Error?>|ai:Error {
        final observe:GenerateContentSpan span = observe:createGenerateContentSpan(self.modelType);
        span.addProvider("openrouter");
        decimal? temperature = self.temperature;
        if temperature is decimal {
            span.addTemperature(temperature);
        }

        DocumentContentPart[]|ai:Error content = generateChatCreationContent(prompt);
        if content is ai:Error {
            span.close(content);
            return content;
        }

        openrouter:ChatGenerationParams request = {
            max_completion_tokens: <decimal>self.maxTokens,
            model: self.modelType,
            messages: [<openrouter:UserMessage>{role: "user", content}],
            'stream: true
        };
        if temperature is decimal {
            request.temperature = temperature;
        }
        span.addInputMessages(request.messages.toJson());

        stream<ai:ChatMessageChunk, ai:Error?>|ai:Error chunks = self.openChunkStream(request, span,
                isolated function(error? err) {
            span.close(err);
        });
        if chunks is ai:Error {
            return chunks;
        }
        // Assigning to an explicitly typed local first; `new (...)` cannot infer
        // the stream type when the function returns a union (`stream<...>|Error`).
        stream<string, ai:Error?> textStream = new (new ChunkTextIterator(chunks));
        return textStream;
    }

    // Opens the SSE stream for `request` and wraps it as a normalized chunk stream. The span
    // is closed here if the connection fails, and by the returned stream's iterator otherwise.
    // `closeSpan` closes `span`; see `SpanCloser` for why it is threaded through separately.
    private isolated function openChunkStream(openrouter:ChatGenerationParams request, observe:LlmSpan span,
            SpanCloser closeSpan) returns stream<ai:ChatMessageChunk, ai:Error?>|ai:Error {
        // The OpenRouter connector deserializes the full response, so streaming
        // uses the raw `streamClient`; copy through the attribution headers.
        map<string|string[]> headers = {};
        foreach [string, anydata & readonly] [key, value] in self.requestHeaders.entries() {
            // Every declared field of `SendChatCompletionRequestHeaders` is a `string` and
            // `init` only ever sets the two attribution headers, so this never widens a
            // value. Going through `toString` rather than filtering on `value is string`
            // keeps a future non-string field from being dropped silently.
            headers[key] = value.toString();
        }

        stream<http:SseEvent, error?>|ai:Error sseStream =
            openSseStream(self.streamClient, "/chat/completions", request, headers);
        if sseStream is ai:Error {
            closeSpan(sseStream);
            return sseStream;
        }
        // Assigning to an explicitly typed local first; `new (...)` cannot infer
        // the stream type when the function returns a union (`stream<...>|Error`).
        stream<ai:ChatMessageChunk, ai:Error?> chunkStream =
            new (new OpenRouterChunkIterator(sseStream, span, closeSpan));
        return chunkStream;
    }

    private isolated function prepareCompletionRequestMessages(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools) returns openrouter:Message[]|ai:Error {
        openrouter:Message[] chatCompletionRequestMessages = [];
        if messages is ai:ChatUserMessage {
            openrouter:UserMessage userMsg = {role: "user", content: check getChatMessageStringContent(messages.content)};
            chatCompletionRequestMessages.push(userMsg);
            return chatCompletionRequestMessages;
        }
        foreach ai:ChatMessage message in messages {
            if message is ai:ChatAssistantMessage {
                chatCompletionRequestMessages.push(self.buildRequestAssistantMessage(message));
            } else if message is ai:ChatUserMessage {
                openrouter:UserMessage userMsg = {role: "user", content: check getChatMessageStringContent(message.content)};
                chatCompletionRequestMessages.push(userMsg);
            } else if message is ai:ChatSystemMessage {
                openrouter:SystemMessage sysMsg = {role: "system", content: check getChatMessageStringContent(message.content)};
                chatCompletionRequestMessages.push(sysMsg);
            } else if message is ai:ChatFunctionMessage {
                // Map legacy function message to tool response; use name as tool_call_id
                openrouter:ToolResponseMessage toolMsg = {
                    role: "tool",
                    content: message.content ?: "",
                    tool_call_id: message.name
                };
                chatCompletionRequestMessages.push(toolMsg);
            }
        }
        return chatCompletionRequestMessages;
    }

    private isolated function buildRequestAssistantMessage(ai:ChatAssistantMessage message)
    returns openrouter:AssistantMessage {
        openrouter:AssistantMessage assistantMessage = {role: "assistant"};
        ai:FunctionCall[]? toolCalls = message.toolCalls;
        if toolCalls is ai:FunctionCall[] && toolCalls.length() > 0 {
            ai:FunctionCall functionCall = toolCalls[0];
            assistantMessage.tool_calls = [
                {
                    id: "call_" + functionCall.name,
                    'type: "function",
                    'function: {
                        name: functionCall.name,
                        arguments: functionCall.arguments.toJsonString()
                    }
                }
            ];
        }
        string? content = message?.content;
        if content is string {
            assistantMessage.content = content;
        }
        return assistantMessage;
    }

    private isolated function convertResponseToAssistantMessage(openrouter:AssistantMessage message)
    returns ai:ChatAssistantMessage|ai:LlmError {
        do {
            ai:ChatAssistantMessage chatAssistantMessage = {role: ai:ASSISTANT};
            anydata? rawContent = message?.content;
            if rawContent is string {
                chatAssistantMessage.content = rawContent;
            }
            openrouter:ChatMessageToolCall[]? toolCalls = message?.tool_calls;
            if toolCalls is openrouter:ChatMessageToolCall[] && toolCalls.length() > 0 {
                // Modern tool_calls path
                ai:FunctionCall[] functionCalls = [];
                foreach openrouter:ChatMessageToolCall toolCall in toolCalls {
                    json arguments = check toolCall.'function.arguments.fromJsonString();
                    functionCalls.push({
                        name: toolCall.'function.name,
                        arguments: check arguments.cloneWithType()
                    });
                }
                chatAssistantMessage.toolCalls = functionCalls;
            } else {
                // Legacy function_call path — AssistantMessage is an open record so the
                // field is still present even though it is not declared on the type.
                map<json>|error legacyCall = message["function_call"].cloneWithType();
                if legacyCall is map<json> {
                    string name = check legacyCall["name"].ensureType();
                    string argsStr = check legacyCall["arguments"].ensureType();
                    json arguments = check argsStr.fromJsonString();
                    chatAssistantMessage.toolCalls = [{
                        name,
                        arguments: check arguments.cloneWithType()
                    }];
                }
            }
            return chatAssistantMessage;
        } on fail error e {
            return error("Invalid or malformed arguments received in function call response.", e);
        }
    }
}

# Posts a streaming chat request and opens the Server-Sent Event stream for the response.
#
# The status code is checked before the stream is opened. `http:Response` as a target type
# suppresses the client's usual non-2xx-to-error mapping, so without this check OpenRouter's
# own message for an expired key, exhausted credits, or a rate limit is discarded, and
# `getSseEventStream` fails the content-type check instead - telling the caller only that
# the stream could not be opened. Reading the error body also drains the payload, which
# releases the connection back to the pool.
#
# + streamClient - The raw HTTP client for the OpenRouter API
# + path - The endpoint path to post to
# + request - The request payload
# + headers - The attribution headers to send with the request
# + return - The SSE event stream, or an `ai:Error` describing the failure
isolated function openSseStream(http:Client streamClient, string path, anydata request,
        map<string|string[]> headers) returns stream<http:SseEvent, error?>|ai:Error {
    http:Response|error response = streamClient->post(path, request, headers);
    if response is error {
        return error ai:LlmConnectionError("Error while connecting to the model for streaming", response);
    }
    int statusCode = response.statusCode;
    if statusCode < 200 || statusCode >= 300 {
        string? detail = extractHttpErrorDetail(response);
        string message = detail is string
            ? string `OpenRouter rejected the streaming request with status ${statusCode}: ${detail}`
            : string `OpenRouter rejected the streaming request with status ${statusCode}`;
        return error ai:LlmConnectionError(message);
    }
    stream<http:SseEvent, error?>|error sseStream = response.getSseEventStream();
    if sseStream is error {
        return error ai:LlmConnectionError("Failed to open the SSE stream from the model", sseStream);
    }
    return sseStream;
}

# Pulls the human-readable detail out of a non-2xx streaming response, which carries the
# usual OpenRouter `{"error": {"message": ...}}` body rather than an event stream. Reading
# it also drains the payload, so the connection is released back to the pool.
#
# + response - The non-2xx response
# + return - The failure detail, or `()` when the body carries none
isolated function extractHttpErrorDetail(http:Response response) returns string? {
    // The body is read exactly once, as text: the first read drains the entity, so probing
    // it as JSON first and falling back to text leaves the fallback with nothing to read.
    // OpenRouter answers a rejected request with a JSON error envelope, but an edge or an
    // upstream provider can put a plain-text body behind the same status.
    string|error text = response.getTextPayload();
    if text is error {
        return ();
    }
    string trimmed = text.trim();
    if trimmed == "" {
        return ();
    }
    json|error payload = trimmed.fromJsonString();
    if payload is error {
        return trimmed;
    }
    string? detail = extractStreamErrorFrame(payload);
    if detail is string {
        return detail;
    }
    return trimmed;
}

# Iterator that converts OpenRouter's Server-Sent Event stream into a stream of
# normalized `ai:ChatMessageChunk` values. Each `data:` line is parsed into the OpenRouter
# wire chunk and mapped via `toAiChatMessageChunk`; the terminating `[DONE]` sentinel ends
# the stream, and blank lines, keep-alive comments, and events that carry nothing for the
# caller (usage-only chunks, a role-only opening delta) are skipped. The span - a `ChatSpan`
# for `chatAsStream` or a `GenerateContentSpan` for `generateAsStream` - is closed once the
# stream is done, whether it ended cleanly, failed, or was closed by the caller.
#
# A frame that cannot be parsed is reported as an error rather than skipped: OpenRouter
# emits `{"error": {...}}` mid-stream when a generation is cut short, and skipping it would
# end the stream silently, handing the caller a truncated answer that looks complete - or,
# if every frame is unparseable, an empty answer that looks successful.
class OpenRouterChunkIterator {
    private stream<http:SseEvent, error?> sseStream;
    private observe:LlmSpan span;
    private SpanCloser closeSpan;
    private boolean done = false;

    isolated function init(stream<http:SseEvent, error?> sseStream, observe:LlmSpan span, SpanCloser closeSpan) {
        self.sseStream = sseStream;
        self.span = span;
        self.closeSpan = closeSpan;
    }

    public isolated function next() returns record {|ai:ChatMessageChunk value;|}|ai:Error? {
        while !self.isDone() {
            record {|http:SseEvent value;|}|error? event = self.sseStream.next();
            if event is () {
                return self.finish();
            }
            if event is error {
                return self.failStream(error ai:LlmConnectionError("Error while reading the model stream", event));
            }
            string? data = event.value.data;
            if data is () {
                continue;
            }
            string trimmedData = data.trim();
            if trimmedData == "" {
                continue;
            }
            if trimmedData == "[DONE]" {
                return self.finish();
            }
            json|error payload = trimmedData.fromJsonString();
            if payload is error {
                return self.failStream(error ai:LlmInvalidResponseError(
                        "Invalid or malformed chunk received from the model", payload));
            }
            string? errorMessage = extractStreamErrorFrame(payload);
            if errorMessage is string {
                return self.failStream(error ai:LlmError(
                        string `Error received mid-stream from the model: ${errorMessage}`));
            }
            CreateChatCompletionStreamResponse|error wireChunk = payload.cloneWithType();
            if wireChunk is error {
                return self.failStream(error ai:LlmInvalidResponseError(
                        "Unexpected chunk shape received from the model", wireChunk));
            }
            self.recordObservations(wireChunk);
            ai:ChatMessageChunk? chunk = toAiChatMessageChunk(wireChunk);
            if chunk is ai:ChatMessageChunk {
                return {value: chunk};
            }
        }
        return ();
    }

    public isolated function close() returns ai:Error? {
        if !self.markDone() {
            self.closeSpan(());
        }
        error? result = self.sseStream.close();
        if result is error {
            return error ai:LlmConnectionError("Error while closing the model stream", result);
        }
        return ();
    }

    // Reports the response id, token usage and raw finish reason carried by `wireChunk` to
    // the span. OpenRouter always sends full usage details on the final chunk.
    private isolated function recordObservations(CreateChatCompletionStreamResponse wireChunk) {
        string? id = wireChunk.id;
        if id is string {
            self.span.addResponseId(id);
        }
        CompletionUsage? usage = wireChunk.usage;
        if usage is CompletionUsage {
            self.span.addInputTokenCount(usage.prompt_tokens);
            self.span.addOutputTokenCount(usage.completion_tokens);
        }
        ChatCompletionStreamChoice[] choices = wireChunk.choices;
        if choices.length() > 0 {
            string? finishReason = choices[0].finish_reason;
            if finishReason is string {
                self.span.addFinishReason(finishReason);
                self.span.addOutputType(observe:TEXT);
            }
        }
    }

    // Ends the stream cleanly, closing the span exactly once.
    private isolated function finish() returns () {
        if !self.markDone() {
            self.closeSpan(());
        }
        return ();
    }

    // Ends the stream with an error, closing the span exactly once.
    private isolated function failStream(ai:Error err) returns ai:Error {
        if !self.markDone() {
            self.closeSpan(err);
        }
        return err;
    }

    private isolated function isDone() returns boolean {
        lock {
            return self.done;
        }
    }

    // Marks the stream as done, returning whether it was already marked before this call.
    private isolated function markDone() returns boolean {
        lock {
            boolean wasDone = self.done;
            self.done = true;
            return wasDone;
        }
    }
}

# Projects a normalized `ai:ChatMessageChunk` stream onto its answer text, yielding each
# non-empty `content` fragment and skipping tool-call, reasoning and finish-only chunks.
# Backs `generateAsStream`; closing it closes the underlying chunk stream.
class ChunkTextIterator {
    private stream<ai:ChatMessageChunk, ai:Error?> chunks;

    isolated function init(stream<ai:ChatMessageChunk, ai:Error?> chunks) {
        self.chunks = chunks;
    }

    public isolated function next() returns record {|string value;|}|ai:Error? {
        while true {
            record {|ai:ChatMessageChunk value;|}|ai:Error? next = self.chunks.next();
            if next is () {
                return ();
            }
            if next is ai:Error {
                return next;
            }
            string? content = next.value.content;
            if content is string && content.length() > 0 {
                return {value: content};
            }
        }
    }

    // `chunks` is the `chatAsStream` stream, whose `close` already returns an `ai:Error`
    // carrying the real failure; re-wrapping it would only bury that message a level down.
    public isolated function close() returns ai:Error? {
        return self.chunks.close();
    }
}
